name: shoes_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/air-max/
    - assets/imgs/air-jordan/
    - assets/imgs/mercurial-vapor/
